$ErrorActionPreference = 'Stop'
$templateRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$pwsh = (Get-Process -Id $PID).Path
$testRoot = Join-Path ([IO.Path]::GetTempPath()) ('mc-mod-template-tests-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $testRoot | Out-Null

function Copy-Template([string]$Name) {
    $destination = Join-Path $testRoot $Name
    New-Item -ItemType Directory -Path $destination | Out-Null
    Get-ChildItem -LiteralPath $templateRoot -Force | Where-Object {
        $_.Name -notin @('build', 'bin', '.gradle', '.gradle-user', '.code-review-graph', '.migration-backup', '.agents')
    } | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $destination $_.Name) -Recurse -Force
    }
    return $destination
}

function Invoke-Init([string]$Root, [string[]]$ExtraArgs, [hashtable]$Environment = @{}) {
    $oldValues = @{}
    foreach ($key in $Environment.Keys) {
        $oldValues[$key] = [Environment]::GetEnvironmentVariable($key, 'Process')
        [Environment]::SetEnvironmentVariable($key, $Environment[$key], 'Process')
    }
    try {
        $script = Join-Path $Root 'scripts\init-template.ps1'
        $output = & $pwsh -NoProfile -ExecutionPolicy Bypass -File $script @ExtraArgs 2>&1
        $exitCode = $LASTEXITCODE
        foreach ($line in $output) { Write-Host $line }
        return [int]$exitCode
    }
    finally {
        foreach ($key in $Environment.Keys) {
            [Environment]::SetEnvironmentVariable($key, $oldValues[$key], 'Process')
        }
    }
}

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw "断言失败：$Message" }
}

$commonArgs = @(
    '-NonInteractive',
    '-ModId', 'sample_mod',
    '-ModName', 'Sample Mod',
    '-ModGroup', 'org.example',
    '-JavaPackage', 'org.example.samplemod',
    '-MainClass', 'SampleMod',
    '-ModVersion', '1.2.3',
    '-Author', 'Template Test',
    '-License', 'MIT',
    '-Description', 'Generated by automated template tests.'
)

try {
    $minimal = Copy-Template 'minimal'
    Assert-True ((Invoke-Init $minimal ($commonArgs + @('-Mode', 'blank'))) -eq 0) '最小项目应初始化成功'
    Assert-True (Test-Path (Join-Path $minimal 'src\main\java\org\example\samplemod\SampleMod.java')) '主类路径应被重命名'
    Assert-True (Test-Path (Join-Path $minimal 'src\main\resources\assets\sample_mod')) '资源命名空间应被重命名'
    Assert-True (Test-Path (Join-Path $minimal '.mcmod-template-state.json')) '应写入初始化状态'
    Assert-True (-not (Test-Path (Join-Path $minimal 'template'))) '初始化后不应保留未选择模块蓝图'
    Assert-True (-not (Test-Path (Join-Path $minimal 'docs\migration-inventory.md'))) '初始化后不应保留模板迁移清单'
    Assert-True ((Invoke-Init $minimal $commonArgs) -ne 0) '重复初始化必须失败'

    $invalid = Copy-Template 'invalid'
    $before = (Get-FileHash (Join-Path $invalid 'gradle.properties')).Hash
    $badArgs = $commonArgs.Clone()
    $badArgs[[array]::IndexOf($badArgs, 'sample_mod')] = 'Bad-Mod'
    Assert-True ((Invoke-Init $invalid $badArgs) -ne 0) '非法 Mod ID 必须失败'
    Assert-True ((Get-FileHash (Join-Path $invalid 'gradle.properties')).Hash -eq $before) '非法输入不得修改项目'

    $full = Copy-Template 'full'
    $fullArgs = $commonArgs + @('-Mode', 'example', '-Modules', 'mixin,config,network,gametest')
    Assert-True ((Invoke-Init $full $fullArgs) -eq 0) '全模块项目应初始化成功'
    foreach ($relative in @(
        'src\main\java\org\example\samplemod\mixin\ExampleMixin.java',
        'src\main\java\org\example\samplemod\config\ExampleConfig.java',
        'src\main\java\org\example\samplemod\network\NetworkHandler.java',
        'src\main\java\org\example\samplemod\gametest\ExampleGameTests.java',
        'src\main\java\org\example\samplemod\client\ClientExample.java'
    )) { Assert-True (Test-Path (Join-Path $full $relative)) "缺少全模块文件：$relative" }

    $rollback = Copy-Template 'rollback'
    $rollbackHash = (Get-FileHash (Join-Path $rollback 'src\main\java\com\example\examplemod\ExampleMod.java')).Hash
    Assert-True ((Invoke-Init $rollback $commonArgs @{ MC_MOD_TEMPLATE_TEST_FAIL_AFTER_WRITE = '1' }) -ne 0) '测试注入故障必须失败'
    Assert-True ((Get-FileHash (Join-Path $rollback 'src\main\java\com\example\examplemod\ExampleMod.java')).Hash -eq $rollbackHash) '故障后必须恢复原始主类'
    Assert-True (-not (Test-Path (Join-Path $rollback '.mcmod-template-state.json'))) '故障后不得留下初始化状态'

    Write-Host '初始化器测试全部通过。'
}
finally {
    if (Test-Path -LiteralPath $testRoot) { Remove-Item -LiteralPath $testRoot -Recurse -Force }
}
